### PR TITLE
proofread intro, changes for consistency and clarity

### PR DESCRIPTION
**Pull request by larskotthoff**
Quite extensive changes, hence submitted as a PR.

### CODE REVIEW

**Comment by pat-s** [comment]
Thanks. Could you please put each sentence on a new line? This makes it easier to review :)

**Comment by larskotthoff** [comment]
Uhh, is there some way I can set up vim to do that?

**Comment by berndbischl** [comment]
Yes. Vim supports the return key. I guess you could also use %s for that, but return is probably easier.

**Comment by berndbischl** [comment]
(Patrick made me do that too...)

**Comment by larskotthoff** [comment]
*grumble* How does that make reviewing easier?

**Comment by pat-s** [comment]
> grumble How does that make reviewing easier?

1. Because you can insert "suggestions" on a per line basis in GH reviews.
1. Also see https://groups.google.com/forum/#!topic/pandoc-discuss/tEWDWL2mLBY (there are even more discussions about that, was too lazy too search for more).
1. Additionally, it is "good practice" to do this.
1. You can visually see if a sentence becomes too long and should maybe be split into two.

**Comment by larskotthoff** [comment]
*grumble* *grumble* fine...

**Comment by berndbischl** [comment]
I really makes diffs more readable

**Comment by berndbischl** [comment]
I know it's a bit annoying... Sorry

**Comment by mllg** [comment]
Thanks Lars!

FWIW, you can easily jump to the beginning of the next sentence with "(" in vim. There are also regular expressions which automatically insert newlines for you. The best way seems to be via formatexpr so that you can "gq" a paragraph: https://vi.stackexchange.com/questions/2846/how-to-set-up-vim-to-work-with-one-sentence-per-line

**Comment by larskotthoff** [comment]
Thanks, yes, that's what I did. Still a bit annoying as this won't really work for everything (lists, code, etc).

**Pull request merged**
