### PR TITLE
Rewriting some intro sections

### PR DESCRIPTION
**Pull request by sumny**
- [ ] 3  Performance Evaluation and Comparison
- [ ] 4  Model Optimization

Both still need some iteration to make things more smooth.
Feature selection feels somewhat out of place in 4.
ROC also is very detailed and somewhat out of place in 3 (because it comes before the essential performance evaluation part).

### CODE REVIEW

**Comment by RaphaelS1** [comment]
@sumny what's the status here?

**Comment by sumny** [comment]
During the last workshop, @be-marc  integrated some parts of the rewritten intro for chapter 4 into his PR(s) (I believe).
Regarding chapter 3, we maybe should discuss this in one of our weekly meetings!

**Comment by sumny** [comment]
@RaphaelS1 chapters: basics, perf, HPO, featsel will get new intros written by @pfistfl & me; this PR will soon be superseded but I'll keep it open until then

**Comment by RaphaelS1** [comment]
Great thank you

**Comment by sumny** [comment]
now superseded by individual PRs. closing.

**Pull request closed without merging**
