### PR TITLE
a set of small suggested modifications for  grammatical accuracy and clarity, in 2: Basics

### PR DESCRIPTION
**Pull request by nickreich**
I finished reading through section 2: Basics and have the attached suggestions. I was going to submit these one section at a time (as I make my way through) but please let me know if you'd prefer them all in one larger PR.

### CODE REVIEW

**Comment by jakob-r** [comment]
I think PRs fo some finer granularity are a good thing. Makes reviewing easier, especially if there is something left to be discussed.
Of course we are happy about all improvements. Thank you!

**Comment by mllg** [comment]
Thanks, Nick! Please consider to add yourself to the list of authors, especially if you keep on improving the book.

**Comment by berndbischl** [comment]
> Thanks, Nick! Please consider to add yourself to the list of authors, especially if you keep on improving the book.

+1 +1 +1

**Comment by nickreich** [comment]
Thanks! Do you mean to add myself to the list of authors for the mlr3 package? (I don't see a separate list of authors for the book itself, although that would seem like a more natural place to list myself based on my contributions so far.)

**Comment by mllg** [comment]
We probably should have a separate list of authors for the book. I'll discuss this with the other guys and then come back to you.

**Pull request merged**
