### PR TITLE
Intro ml prereq

### PR DESCRIPTION
**Pull request by mb706**
Prerequisites chapter

### CODE REVIEW

**Comment by mllg** [comment]
Is still still a draft or ready to me reviewed/merged?

**Comment by mb706** [comment]
Still a draft, sorry, I will try to get this in shape tomorrow

**Comment by mb706** [comment]
Can be reviewed now; I don't know why it is not rendering, to me it doesn't look like I touched anything that should give the error that occurs. It renders fine on my local machine.

**Comment by mllg** [comment]
`Error: Error: Element with key 'unemployment' not found in DictionaryTask!`

That's a pretty helpful error message :)

**Comment by mb706** [comment]
good to hear

**Comment by mllg** [comment]
Installation of mlr3proba is not working. No idea why.

**Comment by mllg** [comment]
Is this superseded by #497 ?

**Comment by mllg** [comment]
@sumny

**Pull request closed without merging**
