### PR TITLE
Feature Selection v2 (Chapter 5)

### PR DESCRIPTION
**Pull request by mnwright**

### CODE REVIEW

**Comment by RaphaelS1** [comment]
@mnwright is this ready for review? I noted some poinits from #490 are addressed but not all, are you planning on addressing the rest (if not just please let me know why)

**Comment by mnwright** [comment]
@berndbischl and me will review next week. We'll also discuss the two remaining open points in #490.

**Comment by mnwright** [comment]
I think this is ready to merge.

**Review by RaphaelS1 — APPROVED** [review]
Amazing thanks. Will discuss with @berndbischl  when he wants me to review again and make final changes but happy to merge for now

**Pull request merged**
