### PR TITLE
ci: replace caching action

### PR DESCRIPTION
**Pull request by sebffischer**
This ensures that we get the offical caching action by github

### CODE REVIEW

**Comment by RaphaelS1** [comment]
@sebffischer can I merge?

**Review by RaphaelS1 — APPROVED** [review]

**Comment by sebffischer** [comment]
@RaphaelS1 I would until https://github.com/mlr-org/mlr3book/pull/753 is merged, as this is more important.

**Comment by RaphaelS1** [comment]
It's merged

**Comment by sebffischer** [comment]
Ok, I fixed the merge conflicts. 
Note that this should not really change a lot I believe, it is just that the action we are using is a fork that is 108 commits behind main: https://github.com/pat-s/always-upload-cache

**Pull request merged**
