### PR TITLE
Netflify PR preview

### LINKED ISSUE #411: Deploy branches / PRs for previewing via netlify
For branches that include either larger chapter rewrites or e.g. changes to the quarto setup etc., it would be nice to have a dedicated rendered version to preview changes (and more quickly gather feedback).

I'm aware of workflows to r.g. render [pkgdown sites for branches](https://github.com/r-lib/pkgdown/blob/main/.github/workflows/pkgdown.yaml#L59-L74) and deploy to netlify, and suspect I could figure out how to set up something like this.

@pat-s, I've been told you're the one to talk to about that 😁

### PR DESCRIPTION
**Pull request by pat-s**
fix #411 

- Netlify cannot install R, hence we need the contents of the `_freeze` folder
- Netflify must install `quarto` via a plugin

Source: https://quarto.org/docs/publishing/netlify.html#rendering-on-netlify

### CODE REVIEW

**Comment by pat-s** [comment]
Blocked by https://github.com/quarto-dev/netlify-plugin-quarto/issues/2.

**Comment by jemus42** [comment]
I see how building via quarto on netlify seems to be the more idiomatic approach, but wouldn't it suffice to do the same as for a bookdown book, where the book is rendered on GitHub Actions and the output folder is pushed to netlify?  
See e.g. here https://github.com/EmilHvitfeldt/bookdown-github-actions-netlify/blob/master/.github/workflows/bookdown.yaml

**Comment by pat-s** [comment]
Maybe, but I am not sure it will work. The linked repo only uses it to publish the final site and not as a preview proxy for PRs. I am not sure if this approach will work for the latter as I don't see any dynamic logic for PRs there. I'll check.

**Comment by jemus42** [comment]
No worries, I just had "I know I saw people have PR previews for bookdown..." in the back of my head - probably based on [this writeup](https://ropensci.org/blog/2020/04/07/bookdown-learnings/#5-how-to-deploy-a-preview-of-the-book-for-pull-requests).

If it ends up being too fiddly though I don't want to belabour the point :)

**Comment by pat-s** [comment]
Thanks, always good to ask and provide resources!

> No worries, I just had "I know I saw people have PR previews for bookdown..." in the back of my head - probably based on [this writeup](https://ropensci.org/blog/2020/04/07/bookdown-learnings/#5-how-to-deploy-a-preview-of-the-book-for-pull-requests).

In general netlify is nothing new, we had it already for the old website and blog. Yet nobody carried it over when the old one was replaced by the new mlr3website repo (as nobody seemed to care about previews), the same applies for the book and the gallery. Good to see some interest in this!

**Pull request closed without merging**
