### PR TITLE
cleanup fonts css

### PR DESCRIPTION
**Pull request by jakob-r**
only use 3 fonts
revert to default line hight

### CODE REVIEW

**Comment by pat-s** [comment]
You did not like the current custom line height and fonts? :/

**Comment by mllg** [comment]
I agree with the font change, but the line height is probably more a question of taste?

**Comment by pat-s** [comment]
ping @jakob-r

**Comment by jakob-r** [comment]
1. Personally I prefer a bigger line hight and it is the default setting, so I changed that.
2. The fonts were strangely configured
2.1 no serifs for the serif style (family 0)
2.2 the list of replacement fonts was quite long e.g.: `Roboto, "Helvetica Neue", Helvetica, Arial, sans`

**Comment by mllg** [comment]
We can do a poll which line height is best, but we should not change fonts based on personal preference. Deviations from the standard are usually not good.

**Comment by berndbischl** [comment]
Michel is completely right. Please don't use an overcomplex setup now, or a nonstandard one. 
We should rather focus on content now, not font size optimization.

**Comment by pat-s** [comment]
I did this several weeks ago and it did not take long. 
Also I do not think that this was an overcomplex change/setup :)
But fair enough now :duck:

**Pull request merged**
