### PR TITLE
add latex-math

### PR DESCRIPTION
**Pull request by sumny**
* `input` statements go in `book/_quarto.yml`
* note that some macros may need changes due to conflicts with `\bm`, `\boldsymbol` and unicode-math

### CODE REVIEW

**Comment by sumny** [comment]
* `\renewcommand` in macros apparently only works properly if we use `pdflatex`
* but switching to `pdflatex` apparently breaks rendering of paradox symbols: `LaTeX Error: Unicode character ∈ (U+2208)`
* trying to fix this with `inputenc` package will result in clash due to `makeidx`
* Maybe @RaphaelS1 can review it and decide how to move forward

**Comment by RaphaelS1** [comment]
I don't really know what I'm looking at, these are just tex files, what's the application to the book?

**Comment by sumny** [comment]
this is needed to have consistent notation in the intros of (at least) chapter 2, 3, 4, because @berndbischl wanted to have some formal introduction as well.

relevant for at least @giuseppec and me but maybe also others.

I just wanted to provide a separate PR so that the individual persons who rely on the tex macros in their intros can merge it own their own in their branch (or we merge it directly in main)

**Comment by RaphaelS1** [comment]
Do you have an example of where this is used?

**Comment by sumny** [comment]
> Do you have an example of where this is used?

see e.g., #462 the intro (still very drafty and too much formalism but according to @berndbischl we should use some notation here)

**Comment by RaphaelS1** [comment]
I think we need to discuss off GH with @berndbischl. To me it doesn't make sense to add this much latex when we aren't using most of it, and from what I can tell there's not enough in the intro to warrant the pain with the macros, we could just use the full commands. I'm also not sure if Basics makes the most sense for the maths, if we put it into the Intro chapter then it's more clearly related to all subsequent chapters (which imo should have 0 maths but only code)

**Comment by sumny** [comment]
as we decided to NOT add that much math, no longer needed

**Pull request closed without merging**
