### PR TITLE
Replace mlr3survival with mlr3proba

### PR DESCRIPTION
**Pull request by adibender**
- some errors in appendix remain

### CODE REVIEW

**Comment by pat-s** [comment]
Thanks. @RaphaelS1 Could you maybe help here resolving the issues?

**Comment by RaphaelS1** [comment]
Sure I can see the problem. I can fix this soon

**Comment by mllg** [comment]
Travis is now complaining that `pec` is not installed.

I'd suggest removing `"surv.rpart"` from the benchmark so that we do not need the `pec` dependency for the book.

**Comment by RaphaelS1** [comment]
Changed to `surv.kaplan` as this is a sensible baseline and only requires `survival`

**Comment by mllg** [comment]
Thanks everyone!

**Pull request merged**
