### PR TITLE
WIP: added paradox vignette to the book

### PR DESCRIPTION
**Pull request by mboecker**
As per https://github.com/mlr-org/paradox/issues/230 I added the paradox vignette to the book. Where do we want this to go? I think right after the learners chapter is a good place, but lets discuss below.

### CODE REVIEW

**Comment by mboecker** [comment]
@jakob-r

**Comment by jakob-r** [comment]
can you delete in in paradox and add to the README where help can be found?

**Comment by jakob-r** [comment]
Could you add names for the chunks?

**Comment by mboecker** [comment]
> Could you add names for the chunks?

done

**Comment by jakob-r** [comment]
Should probably be fine, or do we have to adapt to a style @pat-s ?

**Comment by jakob-r** [comment]
Do we have the newline for new sentence rule?
And also why 03? Isn't that number already taken?

**Comment by mboecker** [comment]
> And also why 03? Isn't that number already taken?

I was waiting on feedback of the chapter ordering. I can change the numbers once we agree on it.

**Comment by pat-s** [comment]
> Do we have the newline for new sentence rule?

yes

> Could you add names for the chunks?

Please stick with https://github.com/mlr-org/mlr3book#chunk-names for chunk names.

Also please follow the ["spacing guide"](https://github.com/mlr-org/mlr3book#spacing) that I just added.

> And also why 03? Isn't that number already taken?

My suggestion would be to put it as 8.1 within `07-optimization`.

**Comment by mboecker** [comment]
> Please stick with https://github.com/mlr-org/mlr3book#chunk-names for chunk names.

I believe I did, since the chapter title is paradox?
I can also fix the other stuff you mentioned, but I dont agree with putting it in the tuning chapter.
Are parameter sets only useful for tuning?

**Comment by jakob-r** [comment]
I think any number that is not taken at the moment should be fine. We will have to reorder it anyhow as soon as we have a tuning chapter.

Also please add a new line after each sentence ending.

**Comment by pat-s** [comment]
> I think any number that is not taken at the moment should be fine. We will have to reorder it anyhow as soon as we have a tuning chapter.

We already have a chapter for tuning and nested resampling.

**Comment by pat-s** [comment]
Merging now and restructuring the order afterwards following the logic that we discussed in the meeting yesterday.

**Pull request merged**
