### PR TITLE
Large scale benchmarking - RS review

### PR DESCRIPTION
**Pull request by RaphaelS1**
@larskotthoff @berndbischl ready for review. Very few changes, mostly just merged some sections and moved a couple things around so it flows a bit better IMO

### CODE REVIEW

**Comment by RaphaelS1** [comment]
@larskotthoff  I don't think I removed anything technical. Could you point to where you mean in [the live book website](https://mlr3book.mlr-org.com/large_benchmarking.html) ?

**Review by larskotthoff — APPROVED** [review]

**Comment by larskotthoff** [comment]
Hmm, looks like the diff is messed up -- live version looks fine.

**Comment by RaphaelS1** [comment]
Great thanks!

**Comment by RaphaelS1** [comment]
Thanks @sebffischer

**Comment by mllg** [comment]
This PR should've been merged earlier, @berndbischl reviewed an outdated version of this chapter. Luckily, @RaphaelS1 already addressed many of the issues. 

I've hijacked this PR (sorry!) and tried to incorporate the remaining suggestions.

**Comment by RaphaelS1** [comment]
@mllg unfortunately not. You appear to have reverted a lot of the chapter when fixing merge conflicts....

* [my first review](https://github.com/mlr-org/mlr3book/pull/610/commits/5eb64cacd0663163e213a70b715d765ae9265002#diff-6f7366d2df1be041e6dc15dc44f789746384efecd60bf021a7ce114b9e5e210d)
* [your merge](https://github.com/mlr-org/mlr3book/pull/610/commits/77a4678eaf2ac97be6b62d0817d8f7eae7b622ca#diff-6f7366d2df1be041e6dc15dc44f789746384efecd60bf021a7ce114b9e5e210d)

**Comment by RaphaelS1** [comment]
I 100% agree some parts should be reverted. But not all

**Comment by mllg** [comment]
Wow don't know how that happened. My merge tool did not show me the changes. Lars reported similar issues - maybe it is best to manually merge in a new branch? I can give it a shot.

**Comment by RaphaelS1** [comment]
Yeah super weird it happened twice.Feel free to fix however works best!!

**Pull request closed without merging**
