### PR TITLE
[WIP]: Tuning use case

### PR DESCRIPTION
**Pull request by pkopper**

### CODE REVIEW

**Comment by jakob-r** [comment]
I am confused. See #124 
Can you consider to write this use-case for our [mlr3gallery](https://github.com/mlr-org/mlr3gallery/)?

paging @mllg

**Comment by pkopper** [comment]
Cheers Jakob for the comment, wasn't aware of the use cases being moved there. 
I'll keep pushing here for the moment, though, until I am told how to post them in the gallery accordingly.

**Comment by mllg** [comment]
This PR started somewhen during the transition to mlr3gallery. I'll just move the use cast to the gallery once it is finished.

**Comment by pat-s** [comment]
@pkopper Please note that you can mark PRs as "draft" rather than prefixing them with "WIP".

**Comment by mllg** [comment]
I did some restructure stuff, therefore you now have some conflicts. I also guess this use case better fits into the gallery. You already have a stand-alone Rnw, so copying this PR over mlr3gallery should be straight forward. Let me know if you need help.

**Comment by pfistfl** [comment]
@pkopper:
Can we merge this into the gallery ASAP?
Please contact me if you need help, but let's get this done soon-ish.
There has not been any progress on this since > 1 month.

**Comment by mllg** [comment]
Is this different from the posts in the gallery? Can we close here?

**Comment by jakob-r** [comment]
As far as I can see the all examples are already in the gallery

- House Price Prediction in King County -> House prices in King County 
- Credit worthiness prediction -> mlr3 basics german credit
- Tuning random forests for credit worthiness assessments -> mlr3tuning Tutorial - German Credit

**Pull request closed without merging**
