### PR TITLE
mlr -> mlr3 transition table 

### PR DESCRIPTION
**Pull request by mboecker**
Items still missing from https://mlr.mlr-org.com/reference/

<details>
<summary>A list of missing items</summary>

- addRRMeasure
- arsq
- bootstrapB
- bootstrapOOB
- brier
- brier.scaled
- capLargeValues
- cindex
- cindex.uno
- createSpatialResamplingPlots
- crossval
- db
- dunn
- expvar
- extractFDAFeatures
- fdr
- featperc
- fixedcv
- friedmanPostHocTestBMR
- generateFeatureImportanceData
- generateHyperParsEffectData
- getClassWeightParam
- getHomogeneousEnsembleModels
- getHyperPars
- getMultilabelBinaryPerformances
- getNestedTuneResultsOptPathDf
- getNestedTuneResultsX
- getOOBPreds
- getProbabilities
- getStackedBaseLearnerPredictions
- getTaskClassLevels
- gmean
- gpr
- growingcv
- hasFunctionalFeatures
- hasLearnerProperties
- hasMeasureProperties
- hasProperties
- iauc.uno
- ibrier
- joinClassLevels
- kappa
- kendalltau
- learnerArgsToControl
- listLearnerProperties
- listLearners
- listMeasureProperties
- listMeasures
- listTaskTypes
- logloss
- lsr
- mae
- makeBaggingWrapper
- makeClassificationViaRegressionWrapper
- makeConstantClassWrapper
- makeCostMeasure
- makeCostSensClassifWrapper
- makeCostSensRegrWrapper
- makeCostSensWeightedPairsWrapper
- makeCustomResampledMeasure
- makeDownsampleWrapper
- makeDummyFeaturesWrapper
- makeExtractFDAFeatMethod
- makeExtractFDAFeatsWrapper
- makeFixedHoldoutInstance
- makeFunctionalData
- makeImputeMethod
- makeImputeWrapper
- makeMeasure
- makeModelMultiplexer
- makeModelMultiplexerParamSet
- makeMulticlassWrapper
- makeMultilabelBinaryRelevanceWrapper
- makeMultilabelClassifierChainsWrapper
- makeMultilabelDBRWrapper
- makeMultilabelNestedStackingWrapper
- makeMultilabelStackingWrapper
- makeOverBaggingWrapper
- makeOversampleWrapper
- makePreprocWrapper
- makePreprocWrapperCaret
- makeRemoveConstantFeaturesWrapper
- makeResampleInstance
- makeSMOTEWrapper
- makeStackedLearner
- makeTuneWrapper
- makeUndersampleWrapper
- makeWeightedClassesWrapper
- makeWrappedModel
- mape
- mcc
- mcp
- meancosts
- medae
- medse
- mergeSmallFactorLevels
- mlrFamilies
- mmce
- mse
- msle
- normalizeFeatures
- npv
- parallelization
- ppv
- qsr
- rae
- reextractFDAFeatures
- regr.featureless
- regr.randomForest
- removeConstantFeatures
- removeHyperPars
- repcv
- rmse
- rmsle
- rrse
- rsq
- sae
- setAggregation
- setHyperPars
- setId
- setMeasurePars
- setPredictThreshold
- setThreshold
- silhouette
- simplifyMeasureNames
- smote
- spearmanrho
- ssr
- subsample
- subsetTask
- testgroup.mean
- testgroup.sd
- timeboth
- timepredict
- timetrain
- TuneControl
- tuneParams
- tuneParamsMultiCrit
- tuneThreshold
- wkappa

</summary>

### CODE REVIEW

**Comment by mboecker** [comment]
The `test.*`, `train.*`, `multilabel.*`, `measure*` and `impute*` functions don't need to be translated right? They are about ~100 functions.

**Comment by pat-s** [comment]
> The test.*, train.*, multilabel.*, measure* and impute* functions don't need to be translated right? They are about ~100 functions.

I assume you mean the S3 functions here? No need for them.

Even in the list above we should not include all items.
It is important that we translate the common ones / user important ones that are actually used in practice. 

For example all the measures can just be redirected in one block (without mentioning every item) to the `mlr_measures` class.

Our approach will not be completely consistent across all functions. Maybe the following helps: 

- Does this function belong to a group of functions? -> Is it used very often in practice by the user? -> If no, block-link. If yes, single-link each function. 

Even in the current blocks we could may be group more stuff together.
`get*`, `set*` and `make*` functions are the important ones followed by the "executers", i.e. `resample()`, `generate*` and so on.

**Comment by pat-s** [comment]
Just FYI: The "formatting errors" were just equal alignments within the blocks done on purpose :)

**Comment by mboecker** [comment]
> Just FYI: The "formatting errors" were just equal alignments within the blocks done on purpose :)

```r
as.data.table(Task)[,Task$feature_names,with = FALSE]
as.data.table(Task)[,        Task$feature_names,      with = FALSE]
```
I feel like the first version is more correct than the second, but if we want to align code like that please let me know! :smiley:

**Comment by pat-s** [comment]
> I feel like the first version is more correct than the second, but if we want to align code like that please let me know! smiley

Took another look -> Sorry, my fault, your commit was totally correct and good! :duck: 	:+1:

**Comment by pat-s** [comment]
@mboecker Are you going to continue here? Meanwhile the transition guide was moved to "04-technical".

**Pull request merged**
